### ISSUE TITLE
Categories hover behaviour

### ISSUE THREAD

**Issue by mp3guy** [28064212/boardsie-enhancement-suite#1]
Is there a way to change the hover behaviour for the category menu? I find it's too sticky and easy to trigger, so when I move the cursor past it to click My Threads, it pops up and prevents me from clicking it.

**Comment by 28064212** [comment]
I might be able to add a delay, but I'd have to see how it would work in practice.

How are you passing through Categories on the way to My Threads? Is this if you're moving the mouse down from the top of the page?

**Comment by mp3guy** [comment]
Exactly, from the bookmark bar and address bar.

**Comment by 28064212** [comment]
Released a new version there, v0.2.21. It introduces a quarter-second delay before the categories menu will display on hovering, so should resolve your issue

**Comment by mp3guy** [comment]
Works great now, thanks!
